### ISSUE TITLE
Strange Topics/Subjects

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-primo#12]
Search for "Ferdinand" gives me topics/subject facets like this:

lehrdegef  (4)
leitfudeu  (2)
ferdhiner  (2)
leitbeuni  (2)
ferdhihib  (1)

Is this a bu, where does it come from?

**Comment by kba** [comment]
No, these are valid subjects from gei-digital. Issue is open to correct this upstream: https://github.com/DM2E/dm2e-mappings/issues/70
